import Layout from "../common/layout/Layout";
import React from "react";

import AboutSection from '../common/section/about/AboutSection';
import OriginImage from '../assets/image/about/origin.jpg';

export default function About() {
    return (
        <Layout color='gray.800'>
            <AboutSection
                aboutTitle='Tentang'
                aboutDescription='Desa Mertelu terletak disisi utara Gunungkidul tepatnya di Desa Mertelu Kecamatan Gedangsari Kabupaten Gunungkidul. Desa wisata Mertelu mengusung konsep wisata Green Village yang menawarkan wisata alam perbukitan dan hutan yang masih terjaga keasriannya. Dari sini dapat dinikmati pemandangan Kota Yogyakarta dan Klaten dari atas ketinggian. Letak Desa yang berada diketinggian menjadikan udaranya sejuk dan segar. Termotivasi dari berkembangnya pariwisata di daerah selatan Gunungkidul yang didominasi oleh wisata pantai dan Goa, masyarakat Desa Mertelu membentuk Kelompok Sadar Wisata (Pokdarwis) untuk menjadi daerah tujuan wisata. Masyarakat berswadaya membentuk desa wisata. Dengan harapan dapat meingkatkan kunjungan wisata ke wilayah utara Gunungkidul dan kemudian berpengaruh kepada peningkatan ekonomi masyarakat. Salah satu daya tarik wisata Desa Mertelu adalah adanya wisata buatan flying fox yang diklaim terpanjang di Indonesia dan terpanjang kedua di Asia Tenggara. Wisatawan dapat meluncur dengan flying fox sepanjang 625m dengan kecepatan mencapai 80 km/jam. Sensasi meluncur diatas ketinggian dengan suguhan pemandangan alam yang asri dapat dinikmati wisatawan. Standar keamanan yang digunakan sudah menggunakna standar internasional. Ketika berkunjung ke Desa Mertelu juga sekaligus dapat berbelanja batik sebagai souvenir. Masyarakat desa setempat banyak yang berprofesi sebagai pembatik dan menghasilkan produk batik tulis maupun batik cap yang cantik. Motif khas Batik Gedangsari adalah motif walang. Selain itu masyarakat juga sangat menjaga tradisi dan budaya agar tetap lestari dan menjadi salah satu daya tarik wisata budaya. (Sumber: https://wisata.gunungkidulkab.go.id/desa-wisata-mertelu)'
                originTitle='Asal Usul'
                originDescription='Mertelu merupakan salah satu desa yang terletak di Kecamatan Gedangsari, Kabupaten Gunungkidul. Asal usul Desa Mertelu dibuktikan dengan keberadaan petilasan migit tiban yang berada di Dukuh Piji, Desa Mertelu. Petilasan tersebut terletak di kompleks Masjid Sunan Kalijaga. Konon posisi migit tersebut berpindah-pindah, pernah berada di Baturturu, Piji (tempat yang sekarang), kemudian berpindah ke Hargomulyo dan kembali lagi ke posisi yang sekarang. Dahulu petilasan migit hanya berupa cungkup yang kemudian kini sudah dilindungi oleh bangunan dari batako dengan model limasan.\nCikal bakal penamaan (toponimi) Desa Mertelu berasal dari kata Mentelu. Kata “Men” didapatkan dari kata “Ngemen-emenke”. Ceritanya dahulu ada wali yang berkunjung ke tempat tersebut. Oleh mbok randha (janda tua) seorang wali tersebut disuguhi 3 nasi golong. Wali tersebut merasa sangat terharu karena mbok randha “ngemen-emenke” memberikan 3 nasi. Kata “Telu” dalam bahasa Jawa berarti “tiga”. Area kompleks tersebut hanya boleh dihuni oleh 3 KK. Satu migit tiban tersebut dan 2 KK warga lainnya. Konon pernah ada yang mendirikan rumah lagi di area tersebut, namun rumah tersebut ditimpa marabahaya yaitu hanyut atau terbakar sehingga hanya menyisakan 3 rumah. Bahkan bukti terbakarnya rumah tersebut masih dapat dilihat hingga sekarang. Hingga kini tidak ada warga yang berani mendirikan rumah di area tersebut.\nDi dekat migit tersebut juga ada padasan untuk tempat air. Konon ada orang yang entah sengaja atau tidak memecahkan padasan tersebut. Kemudian orang tersebut gila hingga akhir hidupnya. Terlepas dari kebenaran pasti cerita, hanya Tuhan yang tahu. Namun terdapat nilai luhur penting dari cerita asal usul Desa Mertelu. Diantaranya yang bisa diteladani adalah sikap mbok randha yang memuliakan tamu dengan menyuguhi nasi.\nMigit Mertelu menjadi tempat dilakukannya upacara bersih desa pada saat peringatan rasulan. Apabila rasulan di migit sudah dimulai, maka daerah di sekitarnya juga baru berani melaksanakan rasulan. Dilakukan upacara tumpeng kenduri sebagai wujud rasa syukur atas rezeki yang dilimpahkan oleh Tuhan. Migit Mertelu juga kerap dijadikan tempat ritual untuk memohon hajat tertentu. Pernah juga dijadikan tempat berdoa untuk meminta hujan. Juru kunci menyarankan agar peziarah yang dating menggunakan migit hanya sebagai tempat berdoa, sehingga tujuan berdoa tetap hanya kepada Tuhan yang Maha Esa.\nDitulis oleh Tim KKN-PPM UGM Periode IV Unit Gedangsari 2022-2023. Sumber: Wawancara dengan Widodo (66 tahun, juru kunci Migit), Suyitna (50 tahun, juru kunci Migit sekaligus Dewan Budaya Mertelu). Gambar: Upacara Bersih Desa Di Petilasan Migit Mertelu. Sumber gambar: Jurnalnusantara.net.'
                originImage={OriginImage}
            />
        </Layout>
    );
};